name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 35.172.229.136
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            echo "Checking Git installation..."
            git --version || echo "Git is not installed!"

            echo "Verifying SSH connection..."
            ssh -T git@github.com || echo "SSH authentication failed"

            echo "Attempting to clone the repository..."
            git clone git@github.com:ridoydey/rkp_ci_cd.git || (cd rkp_ci_cd && git pull origin main)

            echo "Repository cloned successfully."
            echo "Navigating to the project directory..."
            cd rkp_ci_cd

            echo "Removing previous build to free up space..."
            rm -rf .next

            echo "Installing dependencies..."
            npm install
            echo "Dependencies installed successfully."

            echo "Building the project..."
            npm run build
            echo "Project built successfully."

            echo "Installing PM2..."
            npm install -g pm2
            echo "PM2 installed successfully."

            echo "Starting the server using PM2..."
            pm2 restart all || pm2 start npm -- start
            pm2 save

