name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 54.83.79.254
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls
            git clone git@github.com:ridoydey/rkp_ci_cd.git